dj_store_admin/urls.py
from django.urls import path
from .views import *

app_name = 'dj_store_admin'

urlpatterns = [
    path('categorias/', categoriadeproduto_list, name='categoriadeproduto_list'),
    path('categorias/<id>/', categoriadeproduto_detalhes, name='categoriadeproduto_detalhes'),
    path('produtos/<id>/', produto_detalhes, name='produto_detalhes'),
    path('carrinho/', carrinho_detalhes, name='carrinho_detalhes'),
    path('carrinho/limpar/', carrinho_limpar, name='carrinho_limpar'),
]

dj_store_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dj_store_admin.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    })
]

admin.site.site_header = 'DJ Store'
admin.site.index_title = 'Administração da Loja'
admin.site.site_title = 'DJ Store'

dj_store_admin/models.py
from django.db import models

# Create your models here.


class CategoriaDeProduto(models.Model):
    class Meta:
        verbose_name = 'Categoria de produto'
        verbose_name_plural = 'Categorias de produtos'

    nome = models.CharField(max_length=128)

    def __str__(self):
        return self.nome


class Produto(models.Model):
    nome = models.CharField(max_length=128)
    descricao = models.TextField('Descrição')
    categoria = models.ForeignKey(
        CategoriaDeProduto, on_delete=models.CASCADE, related_name='produtos')
    preco = models.FloatField('Preço')

    def __str__(self):
        return self.nome

    @property
    def foto_da_capa(self):
        if self.fotos.count() == 0:
            return None
        return self.fotos.all()[0]


class FotoDeProduto(models.Model):
    class Meta:
        verbose_name = 'Foto de produto'
        verbose_name_plural = 'Fotos de produtos'

    produto = models.ForeignKey(
        Produto, on_delete=models.CASCADE, related_name='fotos')
    arquivo = models.FileField()

    def __str__(self):
        return self.arquivo.name

dj_store_admin/forms.py
from django import forms
from .models import *


class ComprarProdutoForm(forms.Form):
    produto_id = forms.IntegerField(required=True, widget=forms.HiddenInput())
    quantidade = forms.IntegerField()

    def clean(self):
        dados = super().clean()
        produto_id = dados.get('produto_id', None)
        quantidade = dados.get('quantidade', None)
        if not produto_id:
            raise forms.ValidationError('Produto não informado')
        if not Produto.objects.filter(pk=produto_id).exists():
            raise forms.ValidationError('Produto não existe')
        if not quantidade:
            self.add_error(
                'quantidade', 'Informe a quantidade de unidades para comprar')
        if quantidade == 0:
            self.add_error(
                'quantidade', 'A quantidade não pode ser igual a zero')
        if quantidade > 10:
            self.add_error(
                'quantidade', 'Não é permitido comprar mais de 10 unidades do produto')
        return dados

dj_store_admin/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from django.urls import reverse
from .models import *
from .forms import *
# Create your views here.


def categoriadeproduto_list(request):
    categorias = CategoriaDeProduto.objects.all()
    return render(request, 'dj_store_admin/categoriadeproduto_list.html', {'categorias': categorias})


def categoriadeproduto_detalhes(request, id):
    try:
        categoria = CategoriaDeProduto.objects.get(pk=id)
    except CategoriaDeProduto.DoesNotExist:
        return Http404('Esta categoria não foi encontrada')
    return render(request, 'dj_store_admin/categoriadeproduto_detalhes.html', {'categoria': categoria})


def produto_detalhes(request, id):
    try:
        produto = Produto.objects.get(pk=id)
    except Produto.DoesNotExist:
        return Http404('O produto não foi encontrado')
    if request.method == 'GET':
        form = ComprarProdutoForm(initial={'produto_id': produto.id})
    if request.method == 'POST':
        form = ComprarProdutoForm(request.POST)
        if form.is_valid():
            carrinho = request.session.get('carrinho', {})
            dados = form.clean()
            produto_id = str(produto.id)
            if produto_id in carrinho:
                carrinho[produto_id]['quantidade'] += dados['quantidade']
                carrinho[produto_id]['preco_total'] = carrinho[produto_id]['preco_unitario'] * \
                    carrinho[produto_id]['quantidade']
            else:
                carrinho[produto_id] = {
                    'quantidade': dados['quantidade'],
                    'nome': produto.nome,
                    'preco_unitario': produto.preco,
                    'preco_total': produto.preco
                }
            request.session['carrinho'] = carrinho
            return redirect(reverse('dj_store_admin:carrinho_detalhes'))
    return render(request, 'dj_store_admin/produto_detalhes.html',
                  {'form': form, 'produto': produto})


def carrinho_detalhes(request):
    carrinho = request.session.get('carrinho', {})
    preco_total = 0
    for produto_id in carrinho:
        preco_total += carrinho[produto_id]['preco_total']
    if request.method == 'POST':
        acao = request.POST.get('acao', None)
        if acao == 'excluir':
            produto_id = request.POST.get('produto_id', None)
            if produto_id in carrinho:
                carrinho.pop(produto_id, None)
                request.session['carrinho'] = carrinho
    return render(request, 'dj_store_admin/carrinho.html', {'carrinho': carrinho, 'preco_total': preco_total})


def carrinho_limpar(request):
    request.session.flush()
    return redirect(reverse('dj_store_admin:categoriadeproduto_list'))

dj_store_admin/templates/dj_store_admin/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="pt-br">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  {% bootstrap_css %}
  <style type="text/css">
    #contents {
      margin-top: 20px;
    }
  </style>
  {% block extra_head %}
  {% endblock extra_head %}

  <title>{% block title %}{% endblock title %} | DJ Store</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="#">DJS</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">Home</a>
          </li>
          {% url 'dj_store_admin:categoriadeproduto_list' as categorias_url %}
          <li class="nav-item {% if categorias_url in request.path %}active{% endif %}">
            <a class="nav-link" href="{{ categorias_url }}">Categorias</a>
          </li>
          {% url 'dj_store_admin:carrinho_detalhes' as carrinho_url %}
          <li class="nav-item {% if carrinho_url in request.path %}active{% endif %}">
            <a class="nav-link" href="{{ carrinho_url }}">Carrinho de compras</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div id="contents" class="container">
    {% block contents %}
    {% endblock contents %}
  </div>

  <footer>
    <div class="container">
      <p class="small text-muted">dj_store &copy; 2018 &dash; Loja de produtos</p>
    </div>
  </footer>

  {% bootstrap_javascript jquery='full' %}
  {% block document_loaded %}
  {% endblock document_loaded %}
</body>

</html>

dj_store_admin/templates/dj_store_admin/carrinho.html
{% extends "dj_store_admin/base.html" %}
{% block title %}Carrinho{% endblock title %}
{% block contents %}
<h1>Carrinho de compras</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Produto</th>
            <th scope="col">Preço unitário (R$)</th>
            <th scope="col">Quantidade</th>
            <th scope="col">Remover</th>
        </tr>
    </thead>
    <tbody>
        {% for produto_id, item in carrinho.items %}
        <tr>
            <td><a href="{% url 'dj_store_admin:produto_detalhes' produto_id %}">{{ item.nome }}</a></td>
            <td>{{ item.preco_unitario }}</td>
            <td>{{ item.quantidade }}</td>
            <td>
                <form method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="acao" value="excluir">
                    <input type="hidden" name="produto_id" value="{{produto_id}}">
                    <button class="btn btn-warning">Excluir</button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="2">Preço total</td>
            <td colspan="2">R$ {{ preco_total }}</td>
        </tr>
    </tfoot>
</table>
{% endblock contents %}

dj_store_admin/templates/dj_store_admin/categoriadeproduto_detalhes.html
{% extends "dj_store_admin/base.html" %}
{% block title %}Detalhes da categoria {{categoria.nome}}{% endblock title %}
{% block contents %}
<h1>{{ categoria.nome }}</h1>
<h2>Produtos</h2>
<ul>
    {% for produto in categoria.produtos.all %}
    <li><a href="{% url 'dj_store_admin:produto_detalhes' produto.id %}">{{ produto.nome }}</a></li>
    {% endfor %}
</ul>
{% endblock contents %}

dj_store_admin/templates/dj_store_admin/categoriadeproduto_list.html
{% extends "dj_store_admin/base.html" %}
{% block title %}Categorias de produtos{% endblock title %}
{% block contents %}
<h1>Categorias de produtos</h1>
<ul>
    {% for categoria in categorias %}
    <li>
        <a href="{% url 'dj_store_admin:categoriadeproduto_detalhes' categoria.id %}">
            {{ categoria.nome }}
        </a>
    </li>
    {% endfor %}
</ul>
{% endblock contents %}

dj_store_admin/templates/dj_store_admin/produto_detalhes.html
{% extends "dj_store_admin/base.html" %}
{% load bootstrap4 %}
{% block contents %}
<div class="row">
    <div class="col">
        <h1>{{produto.nome}}</h1>
        <div>{{produto.descricao|linebreaks}}</div>
    </div>
    <div class="col-3">
        <h3>Comprar</h3>
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form layout='inline' %}
            {% buttons %}
            <button type="submit" class="btn btn-success">Confirmar</button>
            {% endbuttons %}
        </form>
    </div>
</div>
{% endblock contents %}